# Generated by Django 4.2.11 on 2024-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('owner_number', models.CharField(max_length=20)),
                ('owner_cnic', models.CharField(max_length=15)),
            ],
        ),
    ]
