# Generated by Django 4.2.11 on 2024-04-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managersname', models.CharField(max_length=100)),
                ('managersphonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
