# Generated by Django 4.2.11 on 2024-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=100)),
                ('day_notes', models.TextField()),
            ],
        ),
    ]
