# Generated by Django 4.2.11 on 2024-04-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
