# Generated by Django 4.2.11 on 2024-04-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_route_route_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.daysentry')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salesperson')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shop')),
            ],
        ),
    ]
