# Generated by Django 4.2.11 on 2024-04-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_routing_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='routing_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
