# Generated by Django 4.2.11 on 2024-04-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='crtn_pcs',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
