# Generated by Django 4.2.11 on 2024-04-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_lineitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='salesperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
