# Generated by Django 4.2.11 on 2024-04-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
