# Generated by Django 4.2.11 on 2024-04-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_invoice_routing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
    ]
