# Generated by Django 4.2.11 on 2024-04-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_alter_invoice_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
