# Generated by Django 4.2.11 on 2024-04-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_invoice_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale_types',
            field=models.CharField(choices=[('Whole', 'Whole'), ('Retail', 'Retail')], default='Pending', max_length=10),
        ),
    ]
