# Generated by Django 4.2.11 on 2024-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_invoice_due_date_invoice_sale_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale_types',
            field=models.CharField(choices=[('Whole', 'Whole'), ('Retail', 'Retail')], default='Retail', max_length=10),
        ),
    ]
