# Generated by Django 4.2.11 on 2024-04-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_alter_invoice_sale_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale_types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
