# Generated by Django 4.2.11 on 2024-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_invoice_sale_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
