# Generated by Django 4.2.11 on 2024-04-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_alter_invoice_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
