# Generated by Django 4.2.11 on 2024-04-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_recovery_alter_invoice_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
