# Generated by Django 4.2.11 on 2024-04-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_invoice_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='invoice',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
            preserve_default=False,
        ),
    ]
